name: graphbrainz_example
version: 0.0.1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  http:
  intl:

dev_dependencies:
  test:
  build_runner:
  json_serializable:
  lints: ^3.0.0
  artemis:
    path: ../../.
